
language: go
sudo: required

services:
  - docker

go: 1.5

before_install:
  - sudo service docker stop

install:
  # Replace existing Docker with specific version
  - wget https://test.docker.com/builds/Linux/x86_64/docker-$DOCKER_VERSION -O docker
  - chmod +x docker
  - sudo ./docker daemon --log-level=fatal &
  # Fetch golint and other deps
  - go get github.com/golang/lint/golint
  - go get ./...

script:
  - go vet ./...
  - $GOPATH/bin/golint ./...
  - CGO_ENABLED=0 go build -ldflags "-s -w -X github.com/thriqon/involucro/app.version=$(git describe)" ./.
  - ./involucro --version
  - ./involucro --set REPO=involucro/tool --set TAG=latest wrap-yourself
  - go test -v ./runtime
  - go test -v ./integrationtest

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: ZdT+SuvSTE1iz9Y5mudZIREGz5HYoJjIPanz0h2YrfhUdB4Rgu0hqkjIE9R5gf9mozN0a59xl1FxpeHVGa5K/Qodt3V2owau+OyiuTrdEvcaKvz/BmmfldwNJsqEgttbataDroRw/fwSB2X+tiW0um6D6SUHDkVQt7PIJPxvpwWJJcjXJSHxDru1fm5eASWiCKKB9uj+JPYz0R9smW//kp2S3/7MFTQjg2vU+IwQRxMaMIrcST0DEW33mEW+4zbwA1Bt/rspCFx9ZkdXVjIhIrNmqo7CCJODyvbhJ/WtJ+yfWF+LWEvaznIc+rM4WAkBn+Y+os6wGhGBnDsFi5FfSt6nOxWv+maNfLY7KQiNaWtGCI90PHQce6EGJUefxB1rbIi6LQmGODdCITwrIcrsFOTe8IRKrmOze7VTsJ4QVNHACy6+tDXLzPE64Dvnapx66bElAJ8QPC8JW0KYDaCQmZUp2ygBFhmmzK+TqwZTX3D/ZQul6tzDuCk9f0K+LCL7loLLI866LL7te+3Y3f19nwDAhqkrxB2ExAv6EVBSQQFdcVBGuzlnL4PzQHp9lqEEPHO2qJqYhBIH40hwaIl+F7wXSZIohQRTJbMGljIP71wq55rk94fRfX55Wj7se2I9eBWHQJWZ2S/BNMYlo9St4P/4RukA/dWevGiuy4xYl+o=
    file:
      - involucro
    on:
      tags: true
      repo: thriqon/involucro
      condition: $DOCKER_VERSION=latest

  - provider: script
    skip_cleanup: true
    script: ./push_to_docker.sh
    on:
      condition: $DOCKER_VERSION=latest

notifications:
  irc: "chat.freenode.net#involucro"

env:
  - DOCKER_VERSION=1.9.1
  - DOCKER_VERSION=1.8.3
  - DOCKER_VERSION=1.10.0-rc3
  - DOCKER_VERSION=latest
