
inv.task('wrap-yourself')
	.using('busybox:latest')
		.run('mkdir', '-p', 'dist/tmp/')
		.run('cp', 'involucro', 'dist/')
	.wrap('dist').at('/')
		.withConfig({entrypoint = {'/involucro'}})
		.as(VAR.REPO .. ':' .. VAR.TAG)
	.using('busybox:latest')
		.run('rm', '-rf', 'dist')
