
all: 01 02 03 04 06 09 12 14 15 16 17 20 21 23 26 27 31

01:
	./01_autopull.sh
	./01_compile_and_run.sh

03:
	./03_expectations.sh

02:
	./02_hello_world.sh

04:
	./04_parameters.sh

06:
	./06_timing.sh

09:
	./09_remote_docker.sh

12:
	./12_runtask.sh

14:
	./14_wrapoptions.sh

15:
	./15_nested_dirs.sh

17:
	./17_runoptions.sh

16:
	./16_from_scratch.sh

20:
	./20_tags.sh

21:
	./21_flexible_mount_dir.sh

23:
	./23_env_in_invfile.sh

26:
	./26_correctly_handle_files.sh

27:
	./27_values_from_cli.sh

31:
	./31_literate_mode.sh
