
all: 02 04 06 09 12 14 15 17 bats

02:
	./02_hello_world.sh

04:
	./04_parameters.sh

06:
	./06_timing.sh

09:
	./09_remote_docker.sh

12:
	./12_runtask.sh

14:
	./14_wrapoptions.sh

15:
	./15_nested_dirs.sh

17:
	./17_runoptions.sh

bats:
	@bats .
